from enum import Enum


class ResponseSignals(Enum):


    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_VALIDATION_FAILED = "FILE_VALIDATION_FAILED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_PROCESS_FAILED = "FILE_PROCESS_FAILED"